[package]
name = "eyd"
version = "0.2.0"
edition = "2024"

[dependencies]
serde_json = "1.0"
mountpoints = "0.2"

[dev-dependencies]
tempdir = "0.3"

[profile.release]
opt-level = "z"
panic = "abort"
strip = true
